### ISSUE TITLE
Retrieve all bookshelves of a user

### ISSUE THREAD

**Issue by Relin404** [Eight-Horsepeople-of-the-Graduation/core#41]
Since the frontend team needs a way to display all bookshelves related to one user, we need to implement this feature, starting from the lowest layer (repository) up to highest layers (route, controller).

The bookshelves data returned must follow a specific format _aka_ DTO, with validations rules imposed on each property of such a format.

@rraneemm work your magic!

**Comment by rraneemm** [comment]
It is all done!
